<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Search_wp-post-image</name>
   <tag></tag>
   <elementGuidId>248d16a0-7342-49c0-92ec-8c36a6d35692</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.wp-post-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sticky_bottom_anchor']/div/figure/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e0315067-c03a-4dd4-8b4f-1ed159b6a7cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://kotakoki.wijaysali.my.id/wp-content/themes/the-hanger/images/placeholder.png</value>
      <webElementGuid>2b7d08c5-7b86-4577-8191-7e8a970e9e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Awaiting product image</value>
      <webElementGuid>0e550060-2caa-4fed-a8dd-2126e8844c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-post-image</value>
      <webElementGuid>01092d3d-f7f5-4744-a7a3-8dd5f4de1b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sticky_bottom_anchor&quot;)/div[@class=&quot;woocommerce-product-gallery woocommerce-product-gallery--without-images woocommerce-product-gallery--columns-6 images&quot;]/figure[@class=&quot;woocommerce-product-gallery__wrapper&quot;]/div[@class=&quot;woocommerce-product-gallery__image--placeholder&quot;]/img[@class=&quot;wp-post-image&quot;]</value>
      <webElementGuid>562b25a1-c31e-48f5-b425-34a00bad8abd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sticky_bottom_anchor']/div/figure/div/img</value>
      <webElementGuid>96e98a33-b283-450f-bdd2-07e571a7bb5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Awaiting product image']</value>
      <webElementGuid>c55ed217-8e23-4762-9ecf-ecafb13e9654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure/div/img</value>
      <webElementGuid>8ce2cb93-6cd9-4bfe-8c88-2b195d90bd65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://kotakoki.wijaysali.my.id/wp-content/themes/the-hanger/images/placeholder.png' and @alt = 'Awaiting product image']</value>
      <webElementGuid>685cfbbf-9eab-4c4f-a440-d263b1067fc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
