<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username or E-mail_username-298</name>
   <tag></tag>
   <elementGuidId>9c2d27d4-9474-4a5d-b5c9-54115ac5dac6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#username-298</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='username-298']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41cac66c-1722-4d35-bbef-ac5c795327f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4208b05b-5e2f-417d-a4d6-d7ab24912c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>um-form-field valid </value>
      <webElementGuid>d787eeac-a968-46a6-88d9-b97dc677fa7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4921fdb1-552a-42c9-9330-282dd239369f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username-298</value>
      <webElementGuid>05039b42-0bb6-4fc3-b0f6-e6a2267414bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>username-298</value>
      <webElementGuid>2184b613-811f-41ad-9112-e9c98d22527a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>unique_username_or_email</value>
      <webElementGuid>1e0c6c33-9211-4750-8e2b-6a02c4f7b233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>f3f299bf-6693-4d00-a644-bfb30435803c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;username-298&quot;)</value>
      <webElementGuid>f43dbd28-df47-43ae-bb70-a65bb14bc5e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='username-298']</value>
      <webElementGuid>6fd3946f-b07f-43bf-b3ec-101036b80d7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='um_field_298_username']/div[2]/input</value>
      <webElementGuid>02e093b7-8eb4-4eec-b143-b1f0cc412350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>b0a051f1-15c0-4221-b6da-2f731cfec22f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'username-298' and @id = 'username-298']</value>
      <webElementGuid>bfa23b31-36b9-4cbb-b1fb-a0df9a1956b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
